---
title: "openbiox 公约"
output:
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# openbiox 公约

## 组织名称和建立时间

组织名称：openbiox

组织建立时间：2019年3月

## 宗旨

`Inventing, optimizing, sharing`

## 目标

1. 普及开源科学精神
2. 营造生信开源社区
3. 培育生信优秀人才
4. 孵化生信创新项目

## 组织架构及特点

遵循扁平化管理思想，由常务委员会，项目行动组，资助人三者构成。组织成员在项目进行中无级别关系，杜绝一切对小组发展有害或者分裂小组的行为。

1. **常务委员会：** 每年 3 月初，由全体成员投票选举产生，14-18 人，每一名常务委员会成员应当承担明确的管理职责，任期一年。另需设置 6 人作为常务委员会轮值人员，作为小组管理人才梯队建设项目。第一届常务委员会由创始人团队从第一批成员中筛选，经过临时委员会审核通过，并由全体成员投票选举，得票数前 20-24 人当选。常务委员会换届选举候选人应由当届常务委员会成员提名，并经全体常务委员会成员超过半数同意。一般情况下，常务委员会候选人应当具备以下至少 4-5 个条件（如果是其他特殊人才也可以破格提名）：

    - 对 openbiox 小组有很高的认同感和强烈的参与热情<br>
    - 责任心强<br>
    - 有较强的学习、独立思考和创新能力<br>
    - 有较强的团队协作、项目管理和组织协调能力<br>
    - 在生物信息学社区有一定号召力和影响力<br>
    - 有国家自然科学基金及其他科研项目基金申请经历<br>
    - 有中文核心或者 SCI 文章撰写和发表经历<br>
    - 有发起/贡献开源项目经历<br>
    - 在某些急需的生物信息学研究/应用方向具备特长

    常务委员会主要职责为：

    - 组织团队建设活动<br>
    - 宣传团队项目成果<br>
    - 管理团队资金收支<br>
    - 组织项目创意讨论<br>
    - 分配项目所需资源<br>
    - 监督项目执行进度<br>
    - 评估项目完成情况<br>
    - 监察学术不端

2. **项目行动组：** 由成员自愿选择是否加入，提供小组生物信息学项目设想并开展项目的实际开发、测试、发布、运维。依据项目创意数、成员兴趣、技能等组成实践组。原则上每一个实践组至少含有一名常务委员会成员和一名技术指导人员。

3. **资助人：** 小组内外的个人或机构。所有资助不论金额大小均应登记，全体成员应感谢与珍惜，并适当提供一定特权（如资源的优先使用权、优先内推权利、提供开源项目主页或文档的广告位展示等）。

## 纳新与退出

**纳新机制**

1. 每年 2 月底 3 月初进行线上宣传，以投递简历和邮件申请的方式招收具备高自驱力 openbiox 小组成员。纳新申请需通过常务委员会成员半数同意才准许加入 openbiox 小组。完成集中纳新后，举行常务委员会换届选举，进入下一年度工作计划和流程。
2. 在常务委员会成员任期内，可以由任一常务委员会成员推荐新成员加入，相关推荐人需常务委员会成员半数同意通过。常务委员会成员，每人每年度有 5 人的推荐名额。
3. 由实践项目小组负责人及其负责常务委员会成员共同申请，主要用于招募：项目开展急需的相关专业人员；积极参与开源实践项目并且强烈希望加入 openbiox 小组。相关申请需常务委员会成员半数同意通过。

**会费机制**

为了保证一部分项目的启动经费，以及提高 openbiox 小组成员的项目参与积极性，计划在每年常规纳新结束后，向全体成员收取小组项目建设经费（不超过 100 元），特殊情况（如提供其他方式的等额资助、对小组建设和实践项目有重要贡献）应予以免除和返还。其他非常规纳新时间加入的 openbiox 小组成员也需进行缴纳，特殊情况同上也可以予以免除。

**退出机制**

小组成员想主动退出 openbiox 小组，需向常务委员会进行申请，并注明详细理由，同时需要对其正在负责/参与的项目进行移交，并且放弃该项目可能带来的所有权益（特殊情况由常务委员会和该实践组成员讨论决定）。

openbiox 欢迎所有有热情、有责任心、有想法、有能力、自驱力高的朋友加入。对于长期不关心、不响应、不参与 openbiox 讨论、交流、实践等活动的成员，我们会予以劝导退出（征求其本人最后意见及常务委员会全体成员表决）。

## 成员线上交流形式

与团队活动、工作相关的线上交流和重要信息通知在“钉钉”平台公布，记录留存归档，以备查阅。与生活相关的信息则在“微信群”中发布。

所有生物信息学开源项目的协作均基于开源代码托管网站[GitHub-openbiox](https://github.com/openbiox)开展。其他线上即时交流方式由实践组内部讨论决定，对于部分重要的交流或者事件信息以截图形式分享或保存，以备后期宣传使用。

## 实践项目开展流程
 
创意提出：即兴脑洞（平时任意时间）和集中讨论（3 月份的前两个星期内）。

为防止项目提出的过于泛滥和随意，主要由常务委员会成员发起顿悟脑洞实践项目（无发起时间限制），其可以在其任期内联合其他至少 3 位常务委员会成员在 openbiox 小组内发起不同层次的实践创新项目，获得超半数常务委员会成员同意，并且响应人数符合项目要求后进行启动。其他成员则可以通过和某一常务委员会成员沟通讨论之后发起（常务委员会成员严禁以此索要相关利益，若发生相关情形，将剥夺其常委资格）。

集中讨论则主要在 3 月份的前两个星期内的项目创意会议，期间通过所有 openbiox 小组成员进行头脑风暴，收集和整理所有本年度可能要开展和进行的项目、以及重点要提供人力、资金和设备支持的项目。会议开始时间应在常务委员会确定之后，不晚于 3 月份的第二个星期结束。

项目创意头脑风暴会议结束后，由常务委员会讨论和审核决定本年度要新资助和开展的项目，并由全体成员自由决定是否申请参与。所有非全员参加的实践项目需设置一定参与人数限制和人员筛选要求，并在所有申请人中进行筛选组建成立小团队。每人每年度至少应参与到一个实践小团队中，并贡献至少一个实践项目（不低于一定工作量）。每年度至少应有三次工作量和项目进展考核，对于不合格的或者项目进展不符合预期的小团队进行人员调整和项目进展规划。

对于资金使用量大、人力成本较高的重点支持项目应当提供一份较为详细的项目计划书作  为审核依据，并进行重点审核。主要审核角度主要包括以下的至少 2 项：可行性、创新性、实用性、受众的广泛度、潜在影响力。

项目创意的提出者可以同时选择全程参与项目的完成和发布，最终和项目实践者、组织全体成员共有知识产权，权益比例由前二者商议决定。如果项目产生收益，其中第三部分权益将直接进入组织资源池供 openbiox 项目利用。

所有项目提出、参与、完成、管理者应当在项目完成后撰写项目感悟、思考和收获，并在组织内部或公共媒体宣传发布。

## 项目资源来源、共享和分配

项目资源主要来源于组织内成员捐赠或共享（主要包括经费、设备、场地、技术指导）、组织外赞助（普通用户、商业公司）、高校/机构/国家基金资助、前一年度所有项目的收益分成。

组织拥有的资源均需进入“资源池”，由常务委员会依据项目工作量、使用需求、实践组技能、参与人数量等具体情况进行分配。如果“资源池”在某段时间无法满足支持要求时，可能需要由项目管理者及其常务委员会成员在组织内外发起捐赠或增援倡议。
  
## 拟开展创新实践项目类型

1. 入门和基础型

    - Wiki 百科和百度百科词条的新增和更新
    - 中英文书籍资料的翻译和评论
    - 生物信息学/编程技能相关的文字和视频教程的策划、撰写/录制

2. 进阶提高型

    - 公共数据库和文献的验证、挖掘及其可视化应用开发
    - 数据分析流程的标准化开发和构建
    - 统计和机器学习算法的初阶应用（如历届数学建模大赛题目练习及其报告撰写）
    - 优质开源项目源码的拆解和学习吸收
    - 爬虫类数据收集
   
3. 高阶转化研究型

    - 疾病诊治相关数据库、知识库的收集、整理和构建（如基因检测结果的性状关联，或者癌症基因检测结果的靶点关联）
    - 临床医学数据分析和应用（如基于机器学习等算法的医学图像和影像数据处理、医学诊断及预后预测机器人）
    - 多组学数据整合算法和可视化应用开发；TB/PB 级别数据分析应用开发

## 项目实践成果交流和分享

每年度 10 月份第一周举行组织线下年度会议，由组织成员投票决定举办地点和城市，并尽量获取赞助资源支持会议进行。所有实践项目不论完成与否，均需在年度会议上进行总结和汇报：主要内容包括项目进展过程、成果展示、现场教学和演示、经验总结以及参与人员的收获和思考。现场由参与人员依照一定评分标准进行投票打分，评级 A、B、C 三等。

鉴于很多开源项目会长期进行和维护，在项目完成后，项目负责人和参与人可以选择是否继续进行（将纳入新一年度任务开展计划）或转移相应项目的维护权。若组织内外均无法找到继续维护的负责人，项目将进入 Archive 状态，只保留可读权限。
 
## 项目监管和审核

为了杜绝资源浪费、贪污挪用情况发生，会在每一个实践组中至少安排一位常务委员会成员作为监督员。监督员需要和实践组成员及资源提供者定期沟通，记录和核实资源使用情况。同时，由常务委员会定期对开展的项目进行问询和线上/线下审阅，共同评估项目完成情况、小组成员参与的积极性、小组成员收获和成长，并进行 A，B，C 等级评估。如果连续两次审核均为 C，常务委员会有权进行项目负责人更换或者项目参与人员调整。

如果小组参与人申请退出当前参与项目，需要向该项目负责组长和常务委员会成员申请并说明原因。如果想在项目开展后再参与其他已经开始运作的项目，则需要向对应项目负责组长和常务委员会成员申请同意。

## 其他

1. 所有小组成员应该合理安排时间和各类任务的优先级，需要是在已经完成其日常学习和工作任务之后再参与或者进行 openbiox 的活动讨论以及项目实践。成员如果因为各种不可抗拒因素不能参加相关交流讨论和其负责的项目实践工作，应当向常务委员会成员及其所在实践项目组负责人报备，并请求相关人员进行辅助完成。
2. 小组各类活动通知和自由讨论应当集中在非工作时间（7:00-9:00; 11:30-13:30; 17:00-24:00），避免影响成员的正常工作
3. 常务委员会每两周会进行一次例会，主要讨论内容包括：

    - 人员调整（如纳新和退出的讨论和表决；部门调整；项目成员的新增和剔除）
    - 项目进展安排和计划
    - 总结项目中的经验和遇到的困难，并寻找潜在解决方案
    - 公约及相关制度和资料的修订与完善
    - 资源池变化和使用情况汇报
    - ......
