---
title: "openbiox members"
output:
  md_document: default
  latex_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## openbiox小组成员介绍（排名不分先后）

### 李剑峰
openbiox小组发起人，生信技能树社区核心成员，是开源生物信息学和开放科学思想的坚定支持者、传播者和践行者。上海交通大学医学院附属瑞金医院，医学基因组学国家重点实验室，上海血液学研究所博士生，主要研究方向是生物信息学和白血病。  
[个人博客](https://life2cloud.com) 和 [知乎主页](https://www.zhihu.com/people/life2cloud) 

### 曾健明  
在 [生信菜鸟团博客](http://www.bio-info-trainee.com/)坚持5年持续分享生物信息学相关领域技术知识;
创办广为人知的 [生信技能树论坛](http://www.biotrainee.com/)，是目前全球最大的华语生物信息学专业论坛及公众号;
已经培养了近1万名生信工程师，完成 [全套生物信息学入门及进阶视频教程](https://space.bilibili.com/338686099);
目标 [培养10万名生信工程师](https://mp.weixin.qq.com/s/E9ykuIbc-2Ja9HOY0bn_6g), [2019全国巡讲至少到达60个城市](https://static.dingtalk.com/media/lALPAuoR5z1wDQ3NA_DNAoA_640_1008.png)。

### 赵龙飞  
郑州大学生物信息学博士  

### 许志骁  
华东理工大学在读博士。目前主要进行全基因组和比较基因组方面的分析。负责了实验室的服务器平台的搭建，构建了本课题组的数据分析流程。后期对实验室成员进行了生信相关技能的培训，发展了本课题组的生信团队。  

### 张宇  
本科期间主要研究方向为黄酮醇合成酶的功能验证；现为中国农业科学院硕士研究生，研究方向为代谢组与转录组联用的抗逆代谢调节物检测与验证，请见 [个人ORCID](https://orcid.org/0000-0001-8506-5222) 

### 乔士达  
上海药物研究所 药学硕士  

### 王舒  
复旦大学华山医院血液科博士  

### 张佩  
河北大学与国家蛋白质科学中心联合培养硕士研究生，在国家蛋白质科学中心学习3年。热爱科研，热爱写代码的科研码农。有理想有情怀有热情的，偶尔有些小文艺。  

### 王琪  
R语言办公，C语言生产  

### 魏晨  
大连医科大学 生物医学工程 本科  

### 王灵  
本科临床，硕士流统，目前基础，未来不知  

### 包日强  
上海交通大学医学院附属瑞金医院内分泌在读博士  

### 贾敏  
深圳瑞奥康晨科技有限公司 生信分析工程师  

### 丁雨  
哈尔滨医科大学 生物医学工程 硕士  

### 王海濤  
National Cancer Centre Singapore 新加坡國立癌症中心  

### 陈颖珊  
中国科学院在读博士  

### 袁也  
云南农业大学 植物病理学硕士  

### 阚科佳  
德国海德堡大学曼海姆医学院血管外科博士  

### 杨芮  
山西医科大学第二临床医学院外科学硕士研究生二年级  

### 梁其云  
山东大学海洋学院微生物学在读博士(一年级)  

### 韩漾  
中国科学院大学 生物信息学博士在读  

### 郑东旭  
广州医科大学附属第五医院  

### 王淑轩  
电子科技大学生物物理学硕士  

### 王书喆  
苏黎世联邦理工计算化学博士在读  

### 赵清波  
上海交通大学在读博士，研究方向统计基因组学与生物信息学，专注于遗传多样性保护理论与方法、选择信号、GWAS/GS算法模型开发与应用。热爱统计与编程，喜欢文学，乐于分享与传播。  

### 曾鑫  
东京大学计算生物学与医学硕士生在读  

### 王诗翔  
上海科技大学博士研究生，研究和开发癌症生物标志物  

### 王义冠  
澳大利亚昆士兰大学生物系在读博士  

### 代雨婷  
上海交通大学生物学博士 

### 曾海銮  
复旦大学附属中山医院内分泌科，复旦大学人类表型组研究院，博士生

### 姜思彤  
东北农业大学作物遗传育种硕士  

### 郭奕鑫  
浙江大学医学院免疫所硕士  

### 余超然  
上海交通大学瑞金医院胃肠外科在读博士  

### 熊逸  
中南大学临床医学博士  

### 张子颖  
荷兰瓦赫宁恩大学生物信息学硕士  

### 张楠  
哈尔滨医科大学生物信息学硕士  

### 王慧美  
复旦大学神经生物学硕士  
  
